### PR TITLE
Code clarity update

### PR DESCRIPTION
**Pull request by rkrishnasanka**
The code currently is hard to work with because of the lack of documentation, the crazy number of features pack in and usage of shorthand variables.

This PR tries to improve the situation for the following scenarios:
1. Renaming all struct fields to not have shorthand
2. Replacing redundant variables
3. Ensuring that all type structs are PascalCase rather than camelCase since it messes up exports and makes the code hard to read since there is no difference in the instance names and the typedef. This also has the advantage of making sure that all teh structs are available outside the package scope

### CODE REVIEW

**Comment by dosco** [comment]
Sent you a couple thoughts on discord

**Comment by dosco** [comment]
> 3\. Ensuring that all type structs are PascalCase rather than camelCase since it messes up exports and makes the code hard to read since there is no difference in the instance names and the typedef. This also has the advantage of making sure that all teh structs are available outside the package scope

let me know your thoughts on this since "not exposing" the structs outside the package scope was the point of keeping them camelCase. The idea is that those structs etc are part of the internal API and should not be exposed as they would unnecessarily need to be included in the backward compatibility guarantee slowing down development and also bloating the api documentation.

**Comment by rkrishnasanka** [comment]
@dosco I know this took a long time but I basically undid all the public structs and helped rename a lot of the variables to get a better idea about the flow.

If this is good, I'll restart the multischema support, we definitely need it on our end

**Comment by dosco** [comment]
Thats a huge PR did you manually add these comments or is there a tool that helps?

**Pull request merged**
